# Generated by Django 4.1.6 on 2023-02-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=30)),
                ('id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('estimated_price', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrGenerator.user')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
